[package]
name = "blind-ime"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12"
signal-hook = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arboard = "3.2"